### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by SimonMirleni** [pdepviernestm/presentacion-2022-juanibencardino#1]
Hola Juani, te recomiendo achicar un toque la foto si se puede, así quedaría mucho mas lindo.
![Proud](https://media4.giphy.com/media/Jmy5AY3wagqoBkLV0g/giphy.gif?cid=790b7611otyyo38slcnyohhsskxooi7rrinxftspl6lvnwoz&rid=giphy.gif&ct=g)

**Comment by DGustav** [comment]
x2
